### ISSUE TITLE
heroku vips wont build

### ISSUE THREAD

**Issue by serkisco** [Newlywords/heroku-buildpack-vips#19]
I'm getting this error on Heroku.

Could not open library 'libvips.so.42': libpoppler-glib.so.8: cannot open shared object file: No such file or directory.

So I added an Aptfile with this content:

`libglib2.0-0
libglib2.0-dev
libpoppler-glib8`

I also have these buildpacks in order:

https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/apt.tgz
https://github.com/brandoncc/heroku-buildpack-vips.git
heroku/ruby

I don't want to switch back to imagemagick but I need to get this fixed to continue my build.

**Comment by brandoncc** [comment]
Is your application open source so I can fork it and debug? Or can you make a simple reproduction case app that I can debug? It is sounds like you have it setup correctly, so I'm not sure what is happening. I have heard of people needing to add the node buildpack too in order to make it work, but I was not able to replicate that situation in a test app.

**Comment by brandoncc** [comment]
If it helps you at all, I have [this example app](https://github.com/brandoncc/libvips-test) which is accessible at https://libvips-test.herokuapp.com where you can see it working.

Here are the buildpacks on the application:

```
=== libvips-test Buildpack URLs
1. heroku-community/apt
2. https://github.com/brandoncc/heroku-buildpack-vips
3. heroku/ruby
```

**Comment by serkisco** [comment]
This is what I get when I try to push. No matter what I do, what combinations of buildpacks, it does the same thing. It cannot locate package libglib2.0-0.

Building on the Heroku-18 stack
remote: -----> Using buildpacks:
remote:        1. heroku-community/apt
remote:        2. https://github.com/brandoncc/heroku-buildpack-vips
remote:        3. https://github.com/heroku/heroku-buildpack-activestorage-preview
remote:        4. heroku/nodejs
remote:        5. heroku/ruby
remote: -----> Apt app detected
remote: -----> Detected Aptfile or Stack changes, flushing cache
remote: -----> Updating apt caches
remote:        Hit:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
remote:        Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
remote:        Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
remote:        Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
remote:        Reading package lists...
remote: -----> Fetching .debs for libglib2.0-0
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libglib2.0-0
remote: E: Couldn't find any package by glob 'libglib2.0-0
remote:    '
remote: E: Couldn't find any package by regex 'libglib2.0-0
remote:    '
remote:  !     Push rejected, failed to compile Apt app.
remote:
remote:  !     Push failed
remote: Verifying deploy...

**Comment by brandoncc** [comment]
I see one weird thing that could be related. Is there any chance you have a weird whitespace character after "libglib2.0-0"?

Here is why I ask:

```
remote: E: Couldn't find any package by glob 'libglib2.0-0
remote: ' <==================================== Why was there a line break before this ' ?
remote: E: Couldn't find any package by regex 'libglib2.0-0
remote: ' <==================================== Why was there a line break before this ' ?
```

If you paste the contents of your Aptfile into https://www.soscisurvey.de/tools/view-chars.php, you should be able to see any weird characters that are hiding. Another thing I would try is to delete your Aptfile and then create a new one, typing the letters out by hand instead of copy/pasting them from anywhere.

I wish I could be more help, but I don't know what else could be wrong. Maybe you could find help by opening a ticket on the apt buildpack repo?

Here are my logs for the same part of the build process:

```
-----> Building on the Heroku-18 stack
-----> Using buildpacks:
       1. heroku-community/apt
       2. https://github.com/brandoncc/heroku-buildpack-vips
       3. heroku/nodejs
       4. heroku/ruby
       5. heroku-community/nginx
-----> Apt app detected
-----> Reusing cache
-----> Updating apt caches
       Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
       Hit:2 http://archive.ubuntu.com/ubuntu bionic-security InRelease
       Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
       Hit:4 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
       Reading package lists...
-----> Fetching .debs for libglib2.0-0
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
       Need to get 0 B/1,169 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Download complete and in download only mode
```

**Comment by serkisco** [comment]
Thanks for the clue. I pasted the Aptfile in and what I saw was this.

libglib2.0-0 CR LF
libglib2.0-dev CR LF
libpoppler-glib8

I typed in the new Aptfile manually and it made no difference. I think it's picking up my ENTER keystrokes for the carriage return. Can I write this in one line?

I even created a brand new app, pushed to Heroku and ended up with the same exact issue. I can't be my app. It works fine locally.

**Comment by serkisco** [comment]
Looks like I have it fixed. I figured I'd try to declare all three items in one line like this:

libglib2.0-0 libglib2.0-dev libpoppler-glib8

Instead of the way I had it on three different line, by pressing ENTER.

I pushed the change and everything worked perfectly. Damn carriage returns.

Many days of pulling my hair out but thankfully, this one is over. Thanks again for all the help.

**Comment by brandoncc** [comment]
https://github.com/heroku/heroku-buildpack-apt/issues/53 looks like it is a known issue. You could open a PR to fix it there, if you are interested :-)

**Comment by brandoncc** [comment]
I actually opened a PR. Hopefully they will merge it.

The single-line method you are using is more of a hack, since each package is intended to be processed on its own. I'm glad you got it working though!

**Comment by serkisco** [comment]
I saw your PR. I've never contributed before. Not sure I would've come up with what you did though! Thanks again. I hope this helps anyone else running across the issue.

**Comment by brandoncc** [comment]
You are not the first person that has reported similar issues on my
buildpack, so I really appreciate you following up with the solution
because I have no doubt others will find this useful!
