### ISSUE TITLE
Support for heroku-22 

### ISSUE THREAD

**Issue by kapso** [Newlywords/heroku-buildpack-vips#27]
https://devcenter.heroku.com/articles/heroku-22-stack

**Comment by brandoncc** [comment]
If you would like to add support you can add "22" to the [versions list](https://github.com/brandoncc/heroku-buildpack-vips/blob/master/build.sh#L6) and then run the build script. I have been meaning to drop heroku-16 as well but I haven't done it yet.

**Comment by kapso** [comment]
@brandoncc great I will create a PR

**Comment by kapso** [comment]
@brandoncc actually looks like someone already created a PR for this - https://github.com/brandoncc/heroku-buildpack-vips/pull/26

**Comment by brandoncc** [comment]
Good catch, I hadn't seen that yet. Thanks for bringing up this issue, I appreciate it.
