### ISSUE TITLE
AVIF not working out of the box

### ISSUE THREAD

**Issue by brian-kephart** [Newlywords/heroku-buildpack-vips#31]
Using the heroku-22 stack, I got this error:
```
Vips::Error:
VipsForeignSave: "/tmp/image_processing20220629-52-veut21.avif" is not a known file format
```

Buildpacks:
```
1. heroku-community/apt
2. https://github.com/brandoncc/heroku-buildpack-vips
3. https://github.com/brian-kephart/heroku-buildpack-jemalloc.git
4. https://github.com/heroku/heroku-buildpack-activestorage-preview
5. heroku/ruby
```

Aptfile:
```
libglib2.0-0
libglib2.0-dev
libpoppler-glib8
```

**Comment by brandoncc** [comment]
Hi @brian-kephart, sorry for not responding sooner. Are you on heroku-22? If so, you should be able to load and save avif files now.

**Comment by brandoncc** [comment]
I'm going to close this for now, if you are still having trouble please re-open it and I'll try to get to it quicker this time.
