### ISSUE TITLE
Support for heroku-24

### ISSUE THREAD

**Issue by kapso** [Newlywords/heroku-buildpack-vips#50]
Checking if its possible to support heroku-24

**Comment by edmorley** [comment]
All Heroku stacks now include `libvips`, so the only reason someone should use this buildpack any more is if they need a newer libvips.

However, Ubuntu 24.04's (and thus Heroku-24's) `libvips` version is 8.15.1 - and this is newer than the libvips 8.14.4 included in this buildpack.

As such if you want to use Heroku-24, you can/should remove this buildpack and use the `libvips` that comes with Heroku-24 instead :-)

See:
https://devcenter.heroku.com/articles/stack-packages
https://github.com/dhui5394/heroku-buildpack-vips/releases/tag/8.14.4

**Comment by jrochkind** [comment]
What's the best way to get the `vips` command line on heroku-24, does anyone have any advice? I need the command line not just libvips.

**Comment by cdukes** [comment]
@jrochkind 

Have you tried:

1. Add the https://github.com/heroku/heroku-buildpack-apt buildpack
2. Create an `Aptfile` in your project root with the content `libvips42t64`
3. Push
4. Verify by running `heroku run vips --vips-config`

If that doesn't work, I've forked this buildpack for my own use and updated it for heroku-24: https://github.com/cdukes/heroku-buildpack-vips. I managed to get it working, but for warning - it took quite a bit of trial and error

**Comment by jrochkind** [comment]
@cdukes I have not, but I will!

i never would have come up with package name `libvips42t64`, can you explain where you found that and what it means?  How is it different than just `libvips`?  (And I _thought_ the `libvips` package didn't include command line `vips`, but could be wrong! Lots of moving parts to keep track of here)

I can def spend time trying to find a working recipe, but I'm curious if any of the "experts" have one to recommend, @edmorley ?

**Comment by cdukes** [comment]
libvips42t64 is the package name for the heroku-24 compatible version of the library. You can find it on https://devcenter.heroku.com/articles/stack-packages

**Comment by jrochkind** [comment]
@cdukes interesting, thanks! That says it's a list of "packages that are preinstalled" on each of the heroku stacks, so it should not be necessary to add the packages listed there to Aptfile I think? They should already be preinstalled?

But in the past I thought that pre-installed `libvips` package did not include `vips` command line, but if you're finding it does... I will find some time to experiment on heroku-24 (I don't have a heroku-24 project at present), but also still interested if anyone has all the answers here and can recommend!

**Comment by cdukes** [comment]
I believe 'preinstalled' means 'available in the package repository', not 'directly usable on a clean project install'. So you don't have to compile it yourself, but you still have to tell Heroku to add it to your project. 

I'm not sure if the `libvips42t64` package includes the command line. You can test it with the above steps and `heroku run`. If it doesn't include the command line, you'll have to look at compiling it yourself, which is what my fork of this buildpack was for.

**Comment by jrochkind** [comment]
OK, thanks. I believe you are mistaken about the meaning of "pre-installed". 

Sorry my original question may not have been clear, it is specifically about the `vips` CLI command line utility, and is perhaps for the maintainers of this repo, such as @edmorley who closed this ticket saying "All Heroku stacks now include libvips, so the only reason someone should use this buildpack…" -- I need the `vips` CLI, which I don't believe `libvips` includes.  

Without this buildpack, is there a good suggested way to get get the vips cli?  If so, maybe mention it in the README and in this ticket for those trying to migrate? If not, would it make sense to continue to support this buildpack to get the vips cli? 

Thanks!
