### ISSUE TITLE
Buildpack not compatible with heroku-24 stack

### ISSUE THREAD

**Issue by wrburgess** [Newlywords/heroku-buildpack-vips#53]
My latest build failed after attempting to upgrade from `heroku-22` to `heroku-24` stack 

-----> Build succeeded!
-----> Apt app detected
-----> Detected Aptfile or Stack changes, flushing cache
-----> Updating APT package index
       Get:1 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
       Get:2 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]
       Get:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
       Get:4 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [330 kB]
       Get:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
       Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1,808 kB]
       Get:7 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [329 kB]
       Get:8 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.3 MB]
       Get:9 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [400 kB]
       Get:10 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [424 kB]
       Get:11 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [11.5 kB]
       Get:12 https://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease [129 kB]
       Get:13 https://apt.postgresql.org/pub/repos/apt noble-pgdg/main amd64 Packages [468 kB]
       rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
       Fetched 23.9 MB in 1s (22.5 MB/s)
       Reading package lists...
-----> Fetching .debs for libglib2.0-0
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 25 not upgraded.
       Need to get 1,546 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libglib2.0-0t64 amd64 2.80.0-6ubuntu3.1 [1,546 kB]
       Fetched 1,546 kB in 0s (12.1 MB/s)
       Download complete and in download only mode
-----> Fetching .debs for libglib2.0-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 25 not upgraded.
       Need to get 1,859 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libglib2.0-dev amd64 2.80.0-6ubuntu3.1 [1,859 kB]
       Fetched 1,859 kB in 0s (14.0 MB/s)
       Download complete and in download only mode
-----> Fetching .debs for libpoppler-glib8
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         libpoppler134 poppler-utils
       Recommended packages:
         poppler-data
       The following packages will be upgraded:
         libpoppler-glib8t64 libpoppler134 poppler-utils
       3 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
       Need to get 1,481 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 poppler-utils amd64 24.02.0-1ubuntu9.1 [212 kB]
       Get:2 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libpoppler-glib8t64 amd64 24.02.0-1ubuntu9.1 [157 kB]
       Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libpoppler134 amd64 24.02.0-1ubuntu9.1 [1,113 kB]
       Fetched 1,481 kB in 0s (7,152 kB/s)
       Download complete and in download only mode
-----> Installing libglib2.0-0t64_2.80.0-6ubuntu3.1_amd64.deb
-----> Installing libglib2.0-dev_2.80.0-6ubuntu3.1_amd64.deb
-----> Installing libpoppler134_24.02.0-1ubuntu9.1_amd64.deb
-----> Installing libpoppler-glib8t64_24.02.0-1ubuntu9.1_amd64.deb
-----> Installing poppler-utils_24.02.0-1ubuntu9.1_amd64.deb
-----> Writing profile script
-----> Rewrite package-config files
-----> App not compatible with buildpack: https://github.com/brandoncc/heroku-buildpack-vips
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure

**Comment by leboshi** [comment]
You don't need it anymore :) https://github.com/Newlywords/heroku-buildpack-vips/issues/50#issuecomment-2202334196
