### ISSUE TITLE
vips 8.9.2

### ISSUE THREAD

**Issue by jeffblake** [Newlywords/heroku-buildpack-vips#6]
There's a bug I'm experiencing that vips 8.9.2 fixed, so hoping to get this buildpack updated :) Thanks!

**Comment by brandoncc** [comment]
I'll do it today, thanks for the heads up @jeffblake!

**Comment by brandoncc** [comment]
Sorry I didn't get this done yesterday @jeffblake. I just pushed the update.

**Comment by jeffblake** [comment]
No worries, thanks!
